server:
  servlet:
    context-path: /ExperienceTheWord
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_ETW?serverTimezone=PST
    url: jdbc:mysql://47.254.30.115:3306/db_ETW?serverTimezone=PST
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  aop:
    auto: true
    proxy-target-class: false

